spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: warehouse
      username: "${MONGODB_USERNAME}"
      password: "${MONGODB_PASSWORD}"
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
  address: 0.0.0.0